export const TUNNEL_HEARTBEAT_INTERVAL_MS = 15000;
export const TUNNEL_HEARTBEAT_TIMEOUT_MS = 60000;
export const TUNNEL_HEARTBEAT_GRACE_MS = 0;
export const TUNNEL_HEARTBEAT_STALE_MS =
  TUNNEL_HEARTBEAT_INTERVAL_MS + TUNNEL_HEARTBEAT_TIMEOUT_MS + TUNNEL_HEARTBEAT_GRACE_MS;
export const TUNNEL_HEARTBEAT_CHECK_MS = 5000;
